---
title: "GPGN 598A: Project Proposal"
subtitle: Imaging Mining Induced Perturbations with FWI
# bibliography: references.bib
date: 2023-03-09
author:
  - name: Derrick Chambers
    url: https://derchambers.com
    affiliation: Colorado School of Mines
    affiliation-url: https://mines.edu

format:
  pdf:
    # toc: true
    # toc-depth: 1
    number-sections: true
    colorlinks: true
header-includes:
 \usepackage{wrapfig}
 \usepackage{float}
 \floatplacement{figure}{H}
 \usepackage{amsmath}
---

For the final project, I propose imaging the geological perturbations induced by mining.
Particularly, longwall coal mining.

When material is removed, the ground responds by forming rubblized, fracture, and flexural
zones. For this project, these perturbations will be assumed to occur above the mined out
area and extending in front of the mining face by 15 degrees. The perturbations itself
will be described by 5% decrease in P velocity, 8% decrease in S velocity, and 5% decrease
in density. Sources will occur in the coal ahead of the mining and in the sandstone layers
in the roof and floor behind the mining face. Receivers will be evenly spaced located on the
surface. The initial velocity structure will be a 1D layered model including coal, sandstone,
soil, and shale (@fig-geometry).

The purpose of the exercise is the asses the feasible of various FWI workflows to image
these perturbations in a simplified, yet semi-realistic, geometry. The layered model
(without the perturbations) will be used as the initial model, then the effectiveness of
different misfit functions, kernel pre-conditioning, and other adjustable parameters will
be explored.

![
Problem geometry including sources (stars), receivers(triangle), stratigraphic layers, and
mining-induced perturbations (semi-transparent white region).
](figures/geometry.png){#fig-geometry}
